project_name: trifle

builds:
  - id: trifle
    main: .
    binary: trifle
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"

brews:
  - repository:
      owner: trifle-io
      name: homebrew-trifle
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Formula
    homepage: "https://trifle.io"
    description: "CLI for Trifle time-series metrics"
    license: "ELv2"
    install: |
      bin.install "trifle"
    test: |
      system "#{bin}/trifle", "version"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
